input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(200)
    basic.showIcon(IconNames.Heart)
    basic.showString("Hallo mama")
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(200)
    basic.showIcon(IconNames.Heart)
})
input.onButtonPressed(Button.AB, function () {
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(200)
    basic.showIcon(IconNames.Heart)
    basic.showString("never gotta give you up never gotta let you down never gotta run around and rick roll you")
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(200)
    basic.showIcon(IconNames.Heart)
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(200)
    basic.showIcon(IconNames.Heart)
    basic.showString("Hallo papa")
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(200)
    basic.showIcon(IconNames.Heart)
})
